### ISSUE TITLE
Not working on OS X 10.12.4 with avprobe version 12.2

### ISSUE THREAD

**Issue by mattbucci** [pignacio/gifmaker#4]
AV probe output doesn't contain the resolution or frames in the format you're expecting, I was able to get the data you wanted by adding -show-streams but I still need to change the parsing. maybe there is a better way to patch this? 

```
$ gifmaker BTK\ slide\ template\ GR1.mp4 output.gif
INFO:root:Extracting video data from 'BTK slide template GR1.mp4'
# avprobe output


Traceback (most recent call last):
  File "/usr/local/bin/gifmaker", line 9, in <module>
    load_entry_point('gifmaker==0.0.1', 'console_scripts', 'gifmaker')()
  File "build/bdist.macosx-10.12-intel/egg/gifmaker/__init__.py", line 179, in main
  File "build/bdist.macosx-10.12-intel/egg/gifmaker/__init__.py", line 107, in _extract_video_data
AttributeError: 'NoneType' object has no attribute 'group'

$ avprobe BTK\ slide\ template\ GR1.mp4
avprobe version 12.2, Copyright (c) 2007-2017 the Libav developers
  built on Oct  1 2017 01:28:09 with Apple LLVM version 9.0.0 (clang-900.0.37)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'BTK slide template GR1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2017-10-24 03:17:27
  Duration: 00:00:41.94, start: 0.000000, bitrate: 4205 kb/s
    Stream #0:0(eng): Video: h264 (Main) [avc1 / 0x31637661]
      yuv420p, tv, bt709/bt709/bt709
      764x660, 4057 kb/s
      29.97 fps, 30k tbn (default)
    Metadata:
      creation_time   : 2017-10-24 03:17:27
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
# avprobe output
```
